### ISSUE TITLE
Allow to update notifications

### ISSUE THREAD

**Issue by llicour** [adeo/iwc-tfc-client#6]
**Is your feature request related to a problem? Please describe.**
Seems not to be able to update workspace notification 
ex :
```
notifs = ws.get_list("notification-configurations")
notifs[0].enabled = False   # should disable notif
```

**Describe the solution you'd like**
some hint to fix this : 
> Alors l'objet TFCNotificationConfiguration n'hérite pas de Modifiable. Du coup, pas de modif ... mais c'est peut-être un oublie ... faudrait tester d'ajouter Modifiable sur la class  TFCNotificationConfiguration puis utilise la methode .modify()

**Comment by alex-ikse** [comment]
With the version 0.7.2, you can now write: 
```python
notifs = ws.get_list("notification-configurations")
notifs[0].modify(enabled = False)   # disable first notif of this workspace
```
